sources:
  - name: silver
    description: "Gastos Publicos normalizados"
    schema: silver
    tables:
      - name: gastos
        description: "Tabela de gastos públicos"
        columns:
          - name: orgao
            description: "Nome do órgão"
          - name: pago
            description: "Valor pago em reais"
          - name: ano
            description: "Ano extraído da data"
